// <auto-generated />
namespace SendEmail.WebApp.NetFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewTableContacts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTableContacts));
        
        string IMigrationMetadata.Id
        {
            get { return "202310251138157_NewTableContacts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
